### ISSUE TITLE
I can't run example 

### ISSUE THREAD

**Issue by myblinks** [sun-asterisk-research/stamp_processing#4]
My Code: 
`
import numpy as np
import matplotlib.pyplot as plt
import pdf2image
import cv2
from stamp_processing.detector import StampDetector

def imshow(img, figsize=(10, 10)):
    fig, ax = plt.subplots(1, 1, figsize=figsize)
    ax.axis('off')
    ax.imshow(img)

detector = StampDetector(model_path=None)

images = pdf2image.convert_from_path('sample.pdf')

image = np.array(images[0])

preds = detector.detect([image])
for box in preds[0]:
    cv2.rectangle(image, (box[0], box[1]), (box[2], box[3]), (0, 255, 0), 255)
imshow(image)

`

Run with error:  

`
INFO - Downloading stamp detection weight from google drive'
Cached Downloading: tmp/stamp_detector.pt
Downloading...
From: https://drive.google.com/uc?id=1YHH7pLoZEdyxw2AoLz9G4lrq6uuxweYB
To: /Users/xxx/.cache/gdown/tmpj8u0cjhh/dl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 390k/390k [00:00<00:00, 3.96MB/s]
INFO - Lock 140502501555856 acquired on /Users/xxx/.cache/gdown/_dl_lock'
INFO - Lock 140502501555856 released on /Users/xxx/.cache/gdown/_dl_lock'
INFO - Finished downloading. Weight is saved at tmp/stamp_detector.pt'
Adding autoShape... 
Using cpu for stamp detection
Traceback (most recent call last):
  File "detector.py", line 21, in <module>
    preds = detector.detect([image])
AttributeError: 'StampDetector' object has no attribute 'detect'
`

**Comment by jigsawcoder** [comment]
Facing same issue, please help

**Comment by jigsawcoder** [comment]
> 

This is caused because the method is private to the class and can not be used outside the class as per our use case. What I did is I cloned the repo and changed the name from _detect to detect in detector.py file, and now the detection is working fine.
Suggestion, 
When drawing the bounding box from the predictions, use the following,
for box in preds[0]:
    cv2.rectangle(image, (box[0], box[1]), (box[2], box[3]), (0, 255, 0), 3)
imshow(image)

There is width of the rectangle is changed from 255 to 3.
